# Generated by Django 3.1.2 on 2020-12-01 12:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('ascii_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('avatar_url', models.FileField(blank=True, max_length=1024, null=True, upload_to=core.models.UploadTo('locsharing', 'user'))),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('phone',), name='unique_user_phone'),
        ),
    ]
